"""MineModelingPro — export the unified drill record into modelling-ready tables.

MMP draws on THREE stores and flattens them to two parquet files a modelling
workflow can pick up directly:

  * the government collar backbone      data/keep/mmp.sqlite   (collars, + assays
                                        from 43-101/assessment PDFs as they land)
  * the timely news drill bank          data/keep/drillbank.sqlite (recent full
                                        assays as juniors report them)

Outputs:
  data/keep/mmp_collars.parquet   one row per drill hole (coords, orientation, source)
  data/keep/mmp_assays.parquet    one row per assay interval per element (full downhole)
  data/keep/mmp_deposit_models.parquet  resource/block-model params from 43-101
  data/keep/mmp_collars_sample.csv      quick-look sample

Run:  python -m minemodelingpro.export
"""
import os
import sqlite3
import pandas as pd

from minemodelingpro import store

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
KEEP = os.path.join(_ROOT, "data", "keep")
NEWS_DB = os.path.join(KEEP, "drillbank.sqlite")
MMP_DB = os.path.join(KEEP, "mmp.sqlite")

_COLLAR_COLS = ["hole_uid", "source", "source_kind", "native_id", "company", "project",
                "jurisdiction", "lat", "lon", "easting", "northing", "utm_zone",
                "utm_hemi", "datum", "elev_m", "azimuth", "dip", "depth_m",
                "year_drilled", "has_assay", "assay_flags", "report_ref", "url"]
_ASSAY_COLS = ["hole_uid", "source", "source_kind", "native_id", "project", "jurisdiction",
               "from_m", "to_m", "length_m", "element", "grade", "unit", "is_subinterval"]


def _gov(collars, assays, models):
    if not os.path.exists(MMP_DB):
        return
    con = sqlite3.connect(MMP_DB)
    con.row_factory = sqlite3.Row
    for r in con.execute("SELECT * FROM collars"):
        d = dict(r)
        d["source"] = d.pop("source_id"); d["source_kind"] = "gov_drillholes"
        collars.append({k: d.get(k) for k in _COLLAR_COLS})
    for r in con.execute("SELECT * FROM assays"):
        d = dict(r)
        d["source"] = d.pop("source_id"); d["source_kind"] = "gov_assays"
        d["project"] = None; d["jurisdiction"] = None
        assays.append({k: d.get(k) for k in _ASSAY_COLS})
    try:
        for r in con.execute("SELECT * FROM deposit_model"):
            models.append(dict(r))
    except sqlite3.OperationalError:
        pass
    con.close()


def _news(collars, assays):
    if not os.path.exists(NEWS_DB):
        return
    con = sqlite3.connect(NEWS_DB)
    con.row_factory = sqlite3.Row
    for r in con.execute("""SELECT h.hole_id, r.company, r.project, r.country, r.source, r.url,
               h.easting, h.northing, h.utm_zone, h.utm_hemi, h.datum, h.lat, h.lon,
               h.elev_m, h.azimuth, h.dip, h.depth_m, h.release_id
        FROM holes h JOIN releases r ON h.release_id=r.id"""):
        d = dict(r)
        collars.append({
            "hole_uid": f"news:{d['release_id']}:{d['hole_id']}", "source": d["source"],
            "source_kind": "news", "native_id": d["hole_id"], "company": d["company"],
            "project": d["project"], "jurisdiction": d["country"], "lat": d["lat"], "lon": d["lon"],
            "easting": d["easting"], "northing": d["northing"], "utm_zone": d["utm_zone"],
            "utm_hemi": d["utm_hemi"], "datum": d["datum"], "elev_m": d["elev_m"],
            "azimuth": d["azimuth"], "dip": d["dip"], "depth_m": d["depth_m"],
            "year_drilled": None, "has_assay": 1, "assay_flags": None,
            "report_ref": d["release_id"], "url": d["url"]})
    for r in con.execute("""SELECT i.release_id, r.company, r.project, r.country, r.source,
               i.hole_id, i.is_subinterval, i.from_m, i.to_m, i.length_m, i.element, i.grade, i.unit
        FROM intervals i JOIN releases r ON i.release_id=r.id"""):
        d = dict(r)
        assays.append({
            "hole_uid": f"news:{d['release_id']}:{d['hole_id']}", "source": d["source"],
            "source_kind": "news", "native_id": d["hole_id"], "project": d["project"],
            "jurisdiction": d["country"], "from_m": d["from_m"], "to_m": d["to_m"],
            "length_m": d["length_m"], "element": d["element"], "grade": d["grade"],
            "unit": d["unit"], "is_subinterval": d["is_subinterval"]})
    con.close()


def export(out=KEEP):
    # The gov collar backbone (mmp.sqlite, 100 MB+) is NOT committed — it is
    # regenerated by the mmp-backbone workflow, which owns the mmp_*.parquet
    # outputs. In environments without it (the daily collector, the site CI
    # build), skip export entirely so a news-only run can't clobber the
    # committed 400k-collar backbone parquet.
    if not os.path.exists(MMP_DB):
        print("[mmp] gov store absent — skipping export (owned by mmp-backbone workflow)")
        return {"collars": 0, "assays": 0, "models": 0, "skipped": True}
    # Merge the news bank's recent full-assay releases INTO the working store so
    # the shard store is the single canonical home for all MMP data (gov +
    # 43-101 + news), then persist everything as size-capped per-source shards.
    from minemodelingpro import shards
    _import_news()
    meta = shards.export_shards(MMP_DB)
    # a small quick-look sample from the shards
    dc = shards.load_table("collars")
    if len(dc):
        dc.head(3000).to_csv(os.path.join(out, "mmp_collars_sample.csv"), index=False)
    tot = (meta or {}).get("totals", {})
    print(f"[mmp] shard store: {tot.get('collars',0)} collars, {tot.get('assays',0)} assays, "
          f"{tot.get('lithology',0)} lithology rows across {(meta or {}).get('shard_count',0)} shards")
    return {"collars": tot.get("collars", 0), "assays": tot.get("assays", 0)}


def _import_news():
    """Copy the news bank (drillbank.sqlite) collars + assays into the MMP working
    store under 'news:*' sources, so shards hold the complete record."""
    if not os.path.exists(NEWS_DB):
        return
    collars, assays, _ = [], [], []
    _news(collars, assays)
    if not collars and not assays:
        return
    con = store.connect(MMP_DB)
    crows = [{"hole_uid": c["hole_uid"], "source_id": c["source_kind"] + ":" + str(c["source"]),
              "native_id": c["native_id"], "company": c["company"], "project": c["project"],
              "jurisdiction": c["jurisdiction"], "lat": c["lat"], "lon": c["lon"],
              "easting": c["easting"], "northing": c["northing"], "utm_zone": c["utm_zone"],
              "utm_hemi": c["utm_hemi"], "datum": c["datum"], "elev_m": c["elev_m"],
              "azimuth": c["azimuth"], "dip": c["dip"], "depth_m": c["depth_m"],
              "year_drilled": c["year_drilled"], "has_assay": c["has_assay"],
              "assay_flags": c["assay_flags"], "report_ref": c["report_ref"], "url": c["url"]}
             for c in collars]
    con.execute("DELETE FROM collars WHERE source_id LIKE 'news:%'")
    if crows:
        con.executemany("""INSERT OR REPLACE INTO collars
            (hole_uid,source_id,native_id,company,project,jurisdiction,lat,lon,easting,northing,
             utm_zone,utm_hemi,datum,elev_m,azimuth,dip,depth_m,year_drilled,has_assay,assay_flags,report_ref,url)
            VALUES (:hole_uid,:source_id,:native_id,:company,:project,:jurisdiction,:lat,:lon,:easting,:northing,
             :utm_zone,:utm_hemi,:datum,:elev_m,:azimuth,:dip,:depth_m,:year_drilled,:has_assay,:assay_flags,:report_ref,:url)""", crows)
    con.execute("DELETE FROM assays WHERE source_id LIKE 'news:%'")
    arows = [{"source_id": "news:" + str(a["source"]), "hole_uid": a["hole_uid"],
              "native_id": a["native_id"], "from_m": a["from_m"], "to_m": a["to_m"],
              "length_m": a["length_m"], "element": a["element"], "grade": a["grade"],
              "unit": a["unit"], "is_subinterval": a["is_subinterval"]} for a in assays]
    if arows:
        con.executemany("""INSERT INTO assays
            (source_id,hole_uid,native_id,from_m,to_m,length_m,element,grade,unit,is_subinterval)
            VALUES (:source_id,:hole_uid,:native_id,:from_m,:to_m,:length_m,:element,:grade,:unit,:is_subinterval)""", arows)
    con.commit(); con.close()


if __name__ == "__main__":
    export()
